from Graph import Graph
from Vertex import Vertex

graph = Graph()
vertex1 = Vertex(1,25,100)
graph.addVertex(vertex1)
vertex2 = Vertex(2,75,100)
graph.addVertex(vertex2)
vertex3 = Vertex(3,100,90)
graph.addVertex(vertex3)
vertex4 = Vertex(4,100,40)
graph.addVertex(vertex4)
vertex5 = Vertex(5,75,25)
graph.addVertex(vertex5)
vertex6 = Vertex(6,25,25)
graph.addVertex(vertex6)
vertex7 = Vertex(7,10,50)
graph.addVertex(vertex7)

graph.addEdge(vertex1, vertex7)
graph.addEdge(vertex7, vertex1)
graph.addEdge(vertex7, vertex6)
graph.addEdge(vertex6, vertex7)
graph.addEdge(vertex1, vertex5, 10)
graph.addEdge(vertex5, vertex1, 10)
graph.addEdge(vertex6, vertex5)
graph.addEdge(vertex5, vertex6)
graph.addEdge(vertex5, vertex4)
graph.addEdge(vertex4, vertex5)
graph.addEdge(vertex5, vertex3)
graph.addEdge(vertex3, vertex5)
graph.addEdge(vertex2, vertex3)
graph.addEdge(vertex3, vertex2)
#graph.printGraph()
#graph.findAllPathsDijkstra(vertex1)
#graph.printDijkstraGraph()
#print graph.findPathDijkstra(vertex1, vertex2)
print graph.findPathAStern(vertex1, vertex2)
